export enum IconType {
    Contentful = 'Contentful',
    CSS3 = 'CSS3',
    GraphQL = 'GraphQL',
    HTML5 = 'HTML5',
    Javascript = 'Javascript',
    Next = 'Next',
    NextJsLong = 'NextJsLong',
    Nuxt = 'Nuxt',
    NuxtJsLong = 'NuxtJsLong',
    PHP = 'PHP',
    React = 'React',
    Redux = 'Redux',
    Sass = 'Sass',
    Typescript = 'Typescript',
    Vue = 'Vue',
    Webpack = 'Webpack',
    WordPress = 'WordPress',
    Close = 'Close',
    Github = 'Github',
    LinkedIn = 'LinkedIn',
    Carot = 'Carot',
    MenuButton = 'MenuButton',
    DoubleCarot = 'DoubleCarot',
    Shopify = 'Shopify',
    Netlify = 'Netlify',
    Vercel = 'Vercel',
}
